run:
  timeout: 5m
  skip-dirs:
    - bin

linters-settings:
  goimports:
    local-prefixes: github.com/rudeigerc/dex-operator
  misspell:
    locale: US

linters:
  enable:
    - goimports
    - misspell
    - whitespace
